#!/bin/bash

echo "🚀 DÉPLOIEMENT RENDER + VERCEL - HolyPulse"
echo "============================================="
echo ""

echo "✅ CORRECTIONS APPLIQUÉES:"
echo "   ✓ vite.config.js renommé en vite.config.ts"
echo "   ✓ tsconfig.node.json mis à jour"
echo "   ✓ vercel.json simplifié"
echo "   ✓ Configuration CORS mise à jour"
echo ""

echo "🔴 BACKEND (Laravel) - RENDER:"
echo "================================"
echo "1️⃣  Aller sur https://dashboard.render.com"
echo "2️⃣  New Web Service → Connecter GitHub"
echo "3️⃣  Configuration:"
echo "    • Name: holypulse-backend"
echo "    • Branch: master"
echo "    • Runtime: Docker"
echo "    • Root Directory: (vide)"
echo ""
echo "4️⃣  Variables d'environnement:"
echo "APP_NAME=HolyPulse"
echo "APP_ENV=production"
echo "APP_DEBUG=false"
echo "APP_URL=https://holypulse-projet.onrender.com"
echo "APP_KEY=base64:QmF0dGVyeUJlYXV0aWZ1bEVuZXJneTIwMjUhSG9seVB1bHNl"
echo "DATABASE_URL=postgresql://holy_user:0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu@dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com/holy"
echo "DB_CONNECTION=pgsql"
echo "DB_HOST=dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com"
echo "DB_PORT=5432"
echo "DB_DATABASE=holy"
echo "DB_USERNAME=holy_user"
echo "DB_PASSWORD=0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu"
echo ""

echo "🔵 FRONTEND (Vue.js) - VERCEL:"
echo "==============================="
echo "1️⃣  Aller sur https://vercel.com"
echo "2️⃣  New Project → Import Git Repository"
echo "3️⃣  Configuration:"
echo "    • Project Name: holypulse-front"
echo "    • Framework: Vite"
echo "    • Root Directory: FRONT"
echo "    • Build Command: npm run build"
echo "    • Output Directory: dist"
echo "    • Install Command: npm install"
echo ""
echo "4️⃣  Variables d'environnement:"
echo "VITE_API_BASE_URL=https://holypulse-projet.onrender.com"
echo ""

echo "✅ CE QUI SERA AUTOMATIQUE:"
echo "============================="
echo "📊 BACKEND (Render):"
echo "   ✓ Build Docker automatique"
echo "   ✓ Installation dépendances PHP"
echo "   ✓ Migrations base de données"
echo "   ✓ Configuration Apache"
echo "   ✓ Démarrage sur port 80"
echo ""
echo "🎨 FRONTEND (Vercel):"
echo "   ✓ Build Vue.js + Vite"
echo "   ✓ Optimisation des assets"
echo "   ✓ Déploiement CDN global"
echo "   ✓ HTTPS automatique"
echo ""

echo "🔗 URLS FINALES:"
echo "================"
echo "API Backend:  https://holypulse-projet.onrender.com"
echo "Frontend App: https://holypulse-front.vercel.app"
echo ""

echo "⏱️  Temps de déploiement:"
echo "   Backend (Render): ~8-12 minutes"
echo "   Frontend (Vercel): ~2-3 minutes"
echo ""

echo "🎉 Déploiement prêt ! Les deux services sont configurés correctement."
