#!/bin/bash

echo "🎯 GUIDE DE DÉPLOIEMENT HOLYPULSE - 2 SERVICES SÉPARÉS"
echo "===================================================="
echo ""

echo "✅ Votre projet est configuré pour un déploiement en 2 services:"
echo "   🔴 Backend Laravel (API) → Dockerfile à la racine"
echo "   🔵 Frontend Vue.js → Static Site dans /FRONT"
echo ""

echo "📋 ÉTAPE 1: DÉPLOIEMENT DU BACKEND (API)"
echo "========================================"
echo "1️⃣  Aller sur https://dashboard.render.com"
echo "2️⃣  Cliquer sur 'New +' → 'Web Service'"
echo "3️⃣  Connecter votre repository GitHub"
echo "4️⃣  Configuration:"
echo "    • Name: holypulse-api"
echo "    • Region: Europe (Frankfurt)"  
echo "    • Branch: master"
echo "    • Root Directory: (laisser vide)"
echo "    • Runtime: Docker"
echo "    • Dockerfile Path: ./Dockerfile"
echo ""
echo "5️⃣  Variables d'environnement (IMPORTANTES!):"
echo ""
echo "APP_NAME=HolyPulse"
echo "APP_ENV=production"
echo "APP_DEBUG=false"
echo "APP_URL=https://holypulse-api.onrender.com"
echo "APP_KEY=base64:QmF0dGVyeUJlYXV0aWZ1bEVuZXJneTIwMjUhSG9seVB1bHNl"
echo "DATABASE_URL=postgresql://holy_user:0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu@dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com/holy"
echo "DB_CONNECTION=pgsql"
echo "DB_HOST=dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com"
echo "DB_PORT=5432"
echo "DB_DATABASE=holy"
echo "DB_USERNAME=holy_user"
echo "DB_PASSWORD=0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu"
echo "FRONTEND_URL=https://holypulse-frontend.onrender.com"
echo "SANCTUM_STATEFUL_DOMAINS=holypulse-frontend.onrender.com"
echo ""
echo "📋 ÉTAPE 2: DÉPLOIEMENT DU FRONTEND"
echo "==================================="
echo "1️⃣  Dans le même dashboard, cliquer sur 'New +' → 'Static Site'"
echo "2️⃣  Connecter le même repository"
echo "3️⃣  Configuration:"
echo "    • Name: holypulse-frontend"
echo "    • Branch: master"
echo "    • Root Directory: FRONT"
echo "    • Build Command: npm install && npm run build"
echo "    • Publish Directory: dist"
echo ""
echo "4️⃣  Variables d'environnement:"
echo "VITE_API_BASE_URL=https://holypulse-api.onrender.com"
echo ""
echo "📋 ÉTAPE 3: MISE À JOUR DES CORS"
echo "================================"
echo "Une fois que vous avez les vraies URLs Render, mettez à jour:"
echo "1️⃣  Les variables APP_URL et FRONTEND_URL du backend"
echo "2️⃣  La variable VITE_API_BASE_URL du frontend"
echo "3️⃣  Redéployez les deux services"
echo ""
echo "🚀 RÉSULTAT FINAL:"
echo "=================="
echo "• API Backend: https://holypulse-api.onrender.com"
echo "• Frontend: https://holypulse-frontend.onrender.com"
echo ""
echo "⏱️  Temps estimé total: 10-15 minutes"
echo ""
echo "🎉 Votre application sera complètement fonctionnelle!"
