#!/bin/bash

echo "🚀 DÉPLOIEMENT SIMPLIFIÉ RENDER + VERCEL"
echo "========================================"
echo ""

echo "✅ CORRECTIONS APPLIQUÉES:"
echo "   ✓ Suppression d'Apache (problématique)"
echo "   ✓ Utilisation du serveur PHP intégré de Laravel"
echo "   ✓ Dockerfile simplifié avec php:8.2-cli"
echo "   ✓ Configuration CORS correcte pour Vercel"
echo ""

echo "🔴 BACKEND (Laravel) - RENDER:"
echo "=============================="
echo "1️⃣  https://dashboard.render.com"
echo "2️⃣  New Web Service → GitHub"
echo "3️⃣  Configuration:"
echo "    • Name: holypulse-backend"
echo "    • Branch: master"
echo "    • Runtime: Docker"
echo "    • Root Directory: (vide)"
echo ""
echo "4️⃣  Variables d'environnement (IMPORTANT):"
echo ""
echo "APP_NAME=HolyPulse"
echo "APP_ENV=production"
echo "APP_DEBUG=false"
echo "APP_URL=https://holypulse-projet.onrender.com"
echo "APP_KEY=base64:QmF0dGVyeUJlYXV0aWZ1bEVuZXJneTIwMjUhSG9seVB1bHNl"
echo "DATABASE_URL=postgresql://holy_user:0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu@dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com/holy"
echo "DB_CONNECTION=pgsql"
echo "DB_HOST=dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com"
echo "DB_PORT=5432"
echo "DB_DATABASE=holy"
echo "DB_USERNAME=holy_user"
echo "DB_PASSWORD=0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu"
echo ""

echo "🔵 FRONTEND (Vue.js) - VERCEL:"
echo "=============================="
echo "✅ DÉJÀ EN LIGNE - Rien à faire !"
echo ""

echo "🎯 AVANTAGES DE CETTE APPROCHE:"
echo "================================"
echo "✅ Plus simple (pas d'Apache)"
echo "✅ Plus rapide à démarrer"
echo "✅ Moins de configurations"
echo "✅ Serveur PHP natif de Laravel"
echo "✅ Port 8000 standard"
echo ""

echo "⚡ LE DÉPLOIEMENT VA MAINTENANT:"
echo "==============================="
echo "1. Construire l'image Docker"
echo "2. Installer PHP + extensions PostgreSQL"
echo "3. Installer les dépendances Composer"
echo "4. Configurer Laravel"
echo "5. Exécuter les migrations automatiquement"
echo "6. Démarrer sur php artisan serve (port 8000)"
echo ""

echo "🔗 URLS ATTENDUES:"
echo "=================="
echo "Backend API:  https://holypulse-projet.onrender.com"
echo "Frontend:     https://holypulse-front.vercel.app"
echo ""

echo "⏱️  Temps estimé: 5-8 minutes (plus rapide sans Apache)"
echo ""
echo "🎉 Configuration terminée ! Redéployez maintenant sur Render."
