#!/bin/bash

echo "🔍 DIAGNOSTIC ERROR 500 - HolyPulse"
echo "=================================="
echo ""

echo "✅ CORRECTIONS APPLIQUÉES:"
echo "   ✓ URL Vercel mise à jour: holypulse-projet-l80s01nuw-belalbous-projects.vercel.app"
echo "   ✓ Configuration CORS mise à jour"
echo "   ✓ APP_DEBUG=true pour voir les erreurs"
echo "   ✓ Route / convertie en JSON (plus de vue 'welcome')"
echo "   ✓ Routes de test ajoutées"
echo ""

echo "🔄 POUR REDÉPLOYER:"
echo "=================="
echo "1. Git add & commit:"
echo "   git add ."
echo "   git commit -m 'Fix: URL Vercel + debug routes + CORS'"
echo "   git push"
echo ""
echo "2. Redéployer sur Render (bouton Manual Deploy)"
echo ""

echo "🧪 TESTS À FAIRE APRÈS REDÉPLOIEMENT:"
echo "====================================="
echo "1. Test route principale:"
echo "   https://holypulse-projet.onrender.com/"
echo "   ➜ Devrait retourner JSON avec 'HolyPulse API is running!'"
echo ""
echo "2. Test route santé:"
echo "   https://holypulse-projet.onrender.com/health"
echo "   ➜ Devrait retourner status 'ok'"
echo ""
echo "3. Test route API:"
echo "   https://holypulse-projet.onrender.com/api/test"
echo "   ➜ Devrait retourner 'API is working!'"
echo ""

echo "💡 SI ERREUR 500 PERSISTE:"
echo "=========================="
echo "Vérifiez les logs Render pour voir l'erreur exacte:"
echo "Dashboard → holypulse-backend → Logs"
echo ""
echo "Erreurs possibles:"
echo "• Problème de permissions storage/"
echo "• Erreur de base de données"
echo "• Clé APP_KEY incorrecte"
echo "• Extensions PHP manquantes"
echo ""

echo "🔧 Variables d'environnement importantes à vérifier:"
echo "=================================================="
echo "APP_DEBUG=true (temporaire pour voir les erreurs)"
echo "APP_KEY=base64:sTg0GqM5zrvI3duSC+VsTRi2L6o2weGfNW3BM6Mriqo="
echo "DATABASE_URL=postgresql://holy_user:..."
echo "FRONTEND_URL=https://holypulse-projet-l80s01nuw-belalbous-projects.vercel.app"
