version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: holypulse_db
      MYSQL_USER: holypulse_user
      MYSQL_PASSWORD: holypulse_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - holypulse_network

  # Backend Laravel
  backend:
    build:
      context: ./BACK
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: holypulse_db
      DB_USERNAME: holypulse_user
      DB_PASSWORD: holypulse_password
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:YOUR_APP_KEY_HERE
      CORS_ALLOWED_ORIGINS: "*"
    volumes:
      - ./BACK:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - holypulse_network

  # Frontend Vue.js
  frontend:
    build:
      context: ./FRONT
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - holypulse_network

  # Nginx pour servir en production
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./FRONT/dist:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - holypulse_network

volumes:
  mysql_data:
    driver: local

networks:
  holypulse_network:
    driver: bridge
