#!/bin/bash

echo "🎯 DÉPLOIEMENT FINAL - HolyPulse sur Render"
echo "=========================================="
echo ""

# Vérifier que nous sommes dans le bon répertoire
if [ ! -f "Dockerfile.render" ]; then
    echo "❌ Erreur: Dockerfile.render introuvable. Êtes-vous dans le bon répertoire ?"
    exit 1
fi

echo "✅ Configuration vérifiée:"
echo "   - Base de données: PostgreSQL (dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com)"
echo "   - URL application: https://holypulse-projet.onrender.com"
echo "   - APP_KEY: base64:QmF0dGVyeUJlYXV0aWZ1bEVuZXJneTIwMjUhSG9seVB1bHNl"
echo "   - CORS: Configuré pour holypulse-projet.onrender.com"
echo ""

echo "📋 ÉTAPES DE DÉPLOIEMENT SUR RENDER:"
echo ""
echo "🔴 BACKEND (Laravel API):"
echo "1️⃣  Aller sur https://dashboard.render.com"
echo "2️⃣  Cliquer sur 'New +' → 'Web Service'"
echo "3️⃣  Connecter votre repository GitHub"
echo "4️⃣  Configuration du service backend:"
echo "    • Name: holypulse-backend"
echo "    • Region: Europe (Frankfurt)"
echo "    • Branch: master"
echo "    • Root Directory: (laisser vide)"
echo "    • Runtime: Docker"
echo "    • Dockerfile Path: ./Dockerfile"
echo ""
echo "🔵 FRONTEND (Vue.js Static):"
echo "1️⃣  Créer un nouveau 'Static Site'"
echo "2️⃣  Configuration du frontend:"
echo "    • Name: holypulse-frontend"
echo "    • Branch: master"
echo "    • Root Directory: FRONT"
echo "    • Build Command: npm install && npm run build"
echo "    • Publish Directory: dist"
echo ""
echo "5️⃣  Variables d'environnement à copier-coller:"
echo ""
echo "APP_NAME=HolyPulse"
echo "APP_ENV=production"
echo "APP_DEBUG=false"
echo "APP_URL=https://holypulse-projet.onrender.com"
echo "APP_KEY=base64:QmF0dGVyeUJlYXV0aWZ1bEVuZXJneTIwMjUhSG9seVB1bHNl"
echo "DATABASE_URL=postgresql://holy_user:0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu@dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com/holy"
echo "DB_CONNECTION=pgsql"
echo "DB_HOST=dpg-d15p3h2dbo4c73c2gsf0-a.frankfurt-postgres.render.com"
echo "DB_PORT=5432"
echo "DB_DATABASE=holy"
echo "DB_USERNAME=holy_user"
echo "DB_PASSWORD=0j3VsaVte2QSzolSgEfxdQnMN1Q2KFxu"
echo "FRONTEND_URL=https://holypulse-projet.onrender.com"
echo "SANCTUM_STATEFUL_DOMAINS=holypulse-projet.onrender.com"
echo "SESSION_DOMAIN=.holypulse-projet.onrender.com"
echo ""
echo "6️⃣  Cliquer sur 'Create Web Service'"
echo ""
echo "🚀 Le déploiement va automatiquement:"
echo "   ✅ Construire l'image Docker"
echo "   ✅ Installer les dépendances PHP"
echo "   ✅ Configurer Laravel"
echo "   ✅ Exécuter les migrations"
echo "   ✅ Démarrer l'application"
echo ""
echo "⏱️  Temps estimé: 5-10 minutes"
echo ""
echo "🔗 Une fois déployé, votre API sera accessible à:"
echo "   https://holypulse-projet.onrender.com"
echo ""
echo "📊 Pour vérifier que tout fonctionne:"
echo "   - https://holypulse-projet.onrender.com/api/health (si vous avez une route health)"
echo "   - Vérifiez les logs dans le dashboard Render"
echo ""
echo "🎉 Votre application HolyPulse est prête pour le déploiement!"
